import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import stylesWallpaper from "../styles/Wallpaper.module.css";
import Link from "next/link";
import fondo from "../public/Fondo.jpg";
import { BsLinkedin } from "react-icons/bs";
import {
  AiFillGithub,
  AiFillTwitterCircle,
  AiOutlineWhatsApp,
} from "react-icons/ai";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Pomodoro and ToDo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Reloj.ico" />
      </Head>
      <header className={styles.containerTitle}>
        <h1 className={styles.title}>Pomodoro and ToDo</h1>
        <ul className={styles.containerRedes}>
          <li className={styles.redes}>
            <Link href={"https://www.linkedin.com/in/juli-humere/"}>
              <BsLinkedin />
            </Link>
          </li>
          <li className={styles.redes}>
            <Link href={"https://github.com/Julihumere"}>
              <AiFillGithub />
            </Link>
          </li>
          <li className={styles.redes}>
            <Link href={"https://twitter.com/JuliHumere"}>
              <AiFillTwitterCircle />
            </Link>
          </li>

          <li className={styles.redes}>
            <Link href={"https://walink.co/c55318"}>
              <AiOutlineWhatsApp />
            </Link>
          </li>
        </ul>
      </header>
      <main className={styles.main}>
        <div className={styles.pomodoro}>
          <Link href="/pomodoro">
            <a className={styles.titleElement}>Pomodoro App</a>
          </Link>
        </div>

        <div className={styles.todo}>
          <Link href="/todo">
            <a className={styles.titleElement}>ToDo App</a>
          </Link>
        </div>
      </main>
      <div className={stylesWallpaper.wallpaper}>
        <Image
          layout="fill"
          className={stylesWallpaper.stretch}
          src={fondo}
          alt=""
        />
      </div>
    </div>
  );
}
